### PR TITLE
Issue 40

### LINKED ISSUE #40: redisClient.setBinary should take a byte[] or a Buffer not a String (reference jedis)
```java

byte [] value ....
        redisClient.setBinary(key, value, event -> {
            if (event.failed()) {
                confirmation.onError(event.cause());
            } else {
                confirmation.accept(true);
            }
        });
```

### PR DESCRIPTION
**Pull request by pmlopes**
Fixes #40 
Depends on #41

### CODE REVIEW

**Comment by pmlopes** [comment]
@cescoffier @vietj @purplefox could you review? For Binary payloads the API now uses Buffers and internally i don't do any conversions to/from json.

File: src/main/java/io/vertx/redis/RedisClient.java [hunk 1]
```diff
@@ -830,7 +831,7 @@ static RedisClient create(Vertx vertx, RedisOptions config) {
    * group: string
    */
   @Fluent
-  RedisClient getBinary(String key, Handler<AsyncResult<String>> handler);
+  RedisClient getBinary(String key, Handler<AsyncResult<Buffer>> handler);
```
Comment (cescoffier) [inline src/main/java/io/vertx/redis/RedisClient.java]: Breaking change - should be listed or avoided.

Comment (pmlopes) [inline src/main/java/io/vertx/redis/RedisClient.java]: it is already listed ;)

Comment (cescoffier) [inline src/main/java/io/vertx/redis/RedisClient.java]: Perfect !

File: src/main/java/io/vertx/redis/RedisClient.java [hunk 2]
```diff
@@ -1833,7 +1834,20 @@ static RedisClient create(Vertx vertx, RedisOptions config) {
...
+  RedisClient setBinary(String key, Buffer value, Handler<AsyncResult<Void>> handler);
+
+  /**
+   * Set the string value of a key
+   *
+   * @param key     Key of which value to set
+   * @param value   New value for the key
+   * @param options Set options
+   * @param handler Handler for the result of this call.
+   * @since 1.0.0
```
Comment (cescoffier) [inline src/main/java/io/vertx/redis/RedisClient.java]: I don't get the @since here. Aren't we in 3.2.0 ?

File: src/main/java/io/vertx/redis/RedisClient.java [hunk 3]
```diff
@@ -1833,7 +1834,20 @@ static RedisClient create(Vertx vertx, RedisOptions config) {
...
+   * group: string
```
Comment (cescoffier) [inline src/main/java/io/vertx/redis/RedisClient.java]: I don't get this either.

**Comment by cescoffier** [comment]
Two small question about a javadoc comment. The rest looks good.

File: src/main/java/io/vertx/redis/RedisClient.java (hunk 2 above)
Comment (pmlopes) [inline src/main/java/io/vertx/redis/RedisClient.java]: that is the redis server api level all methods are annotated with the redis api server that supports it, it was something that was copied from the original client that i wrote. I can remove them all since the javadoc annotation does not refer to the API version

Comment (cescoffier) [inline src/main/java/io/vertx/redis/RedisClient.java]: oh, well, I think it's a valuable information. Maybe instead of just @since, add something like @since Redis 1.0.0 to indicate it refers to Redis version and not the version of the current API.

**Comment by pmlopes** [comment]
Sure it is a simple find/replace
